[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Download micro-ROS, Adafruit IMU libraries, and the hardware Encoder library
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    adafruit/Adafruit MPU6050 @ ^2.2.9
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    madhephaestus/ESP32Encoder @ ^0.11.8

; micro-ROS specific configuration
board_microros_distro = jazzy
board_microros_transp`ort = serial


; [env:esp32-s3-devkitc-1]
; platform = esp32-s3-devkitc-1
; board = esp32dev
; framework = arduino
; monitor_speed = 115200

; ; Optional but recommended
; upload_speed = 921600
; build_flags = 
;     -D CORE_DEBUG_LEVEL=0